## Singular Value Decomposition

Singular Value Decomposition is a generalisation of the Eigendecomposition method and is applicable on any type of Matrix.It's very intutive when dealing with finding hidden factors.

In [83]:
import pandas as pd
import numpy as np
np.set_printoptions(precision=2)

In [84]:
np.version.version

'1.18.1'

In [85]:
dat = pd.read_csv('MyFoodRatings.csv')
dat = dat.drop(['Name'], axis=1)
dat

Chicken  Mutton  Paneer  ChowMein  SpringRolls  Momo  Sushi  Ramen  \
0         5       5       5         0            0     0      0      0   
1         4       4       4         0            0     0      0      0   
2         3       3       3         0            0     0      0      0   
3         2       2       2         0            0     0      0      0   
4         0       0       0         2            2     2      0      0   
5         0       0       0         1            1     1      0      0   
6         0       0       0         5            3     4      0      0   
7         0       0       0         4            4     4      0      0   
8         0       0       0         0            0     0      2      2   
9         0       0       0         0            0     0      1      1   
10        0       0       0         0            0     0      3      4   
11        0       0       0         0            0     0      2      2   

    Tempura  
0         0  
1         0  
2         0  
3         0  
4         0  
5         0  
6         0  
7         0  
8         4  
9         1  
10        4  
11        2

In [86]:
U,s,VT = np.linalg.svd(dat, full_matrices = True)

In [87]:
#Also known as the matrix that shows the effect of each row on the themes
U 

array([[-0.68,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.68, -0.26,
         0.  ,  0.  ,  0.  ],
       [-0.54,  0.  ,  0.  , -0.  ,  0.  ,  0.  , -0.44, -0.29,  0.65,
        -0.02,  0.06, -0.03],
       [-0.41,  0.  ,  0.  , -0.  ,  0.  ,  0.  , -0.  , -0.65, -0.64,
        -0.  ,  0.  , -0.  ],
       [-0.27, -0.  , -0.  ,  0.  , -0.  , -0.  ,  0.88, -0.15,  0.32,
         0.03, -0.11,  0.06],
       [ 0.  , -0.33, -0.  ,  0.  , -0.29, -0.  , -0.13,  0.  ,  0.  ,
         0.22, -0.74,  0.44],
       [ 0.  , -0.16,  0.  , -0.  , -0.14,  0.  ,  0.02,  0.  ,  0.  ,
         0.34,  0.62,  0.67],
       [ 0.  , -0.66,  0.  ,  0.  ,  0.75, -0.  ,  0.  ,  0.  ,  0.  ,
         0.  , -0.  ,  0.  ],
       [ 0.  , -0.65,  0.  , -0.  , -0.58,  0.  ,  0.06,  0.  ,  0.  ,
        -0.19,  0.22, -0.39],
       [ 0.  ,  0.  , -0.54, -0.84,  0.  ,  0.08,  0.  ,  0.  ,  0.  ,
        -0.  , -0.  , -0.  ],
       [ 0.  ,  0.  , -0.19,  0.16,  0.  ,  0.37,  0.  ,  0.  ,  0.  ,
         0.8 , -0.  

In [88]:
U.shape

(12, 12)

In [89]:
b = ['A','B','C','D','E','F','G','H','I','J','K','L']
dt = pd.DataFrame(U,columns = b)
dt

A             B             C             D             E  \
0  -0.680414  0.000000e+00  0.000000e+00  2.589087e-33  0.000000e+00   
1  -0.544331  4.965068e-17  3.858566e-18 -1.783526e-17  2.482534e-16   
2  -0.408248  4.385591e-33  3.197739e-34 -7.066453e-34  1.218717e-32   
3  -0.272166 -9.930137e-17 -7.717132e-18  3.567052e-17 -4.965068e-16   
4   0.000000 -3.262170e-01 -5.183871e-17  2.396116e-16 -2.899287e-01   
5   0.000000 -1.631085e-01  9.778593e-17 -2.467328e-16 -1.449643e-01   
6   0.000000 -6.643101e-01  2.624092e-33  2.332361e-33  7.474571e-01   
7   0.000000 -6.524340e-01  1.472874e-18 -5.812257e-17 -5.798574e-01   
8   0.000000  0.000000e+00 -5.410479e-01 -8.368126e-01  0.000000e+00   
9   0.000000  0.000000e+00 -1.936803e-01  1.621542e-01  0.000000e+00   
10  0.000000  0.000000e+00 -7.209069e-01  4.102129e-01  0.000000e+00   
11  0.000000  0.000000e+00 -3.873606e-01  3.243085e-01  0.000000e+00   

               F             G         H         I             J  \
0   0.000000e+00  0.000000e+00  0.683952 -0.263148  1.457527e-18   
1   8.150160e-17 -4.422819e-01 -0.292768  0.646522 -1.624405e-02   
2   3.184178e-33 -4.798228e-17 -0.651973 -0.638956 -1.003467e-18   
3  -1.630032e-16  8.845638e-01 -0.146384  0.323261  3.248810e-02   
4  -1.094950e-15 -1.332510e-01  0.000000  0.000000  2.182341e-01   
5   1.860201e-15  1.567659e-02  0.000000  0.000000  3.371229e-01   
6  -9.483700e-32  4.876544e-16  0.000000  0.000000  2.247629e-17   
7   8.242500e-17  6.270636e-02  0.000000  0.000000 -1.933978e-01   
8   8.373615e-02  0.000000e+00  0.000000  0.000000 -6.782982e-17   
9   3.690446e-01  0.000000e+00  0.000000  0.000000  8.000000e-01   
10 -5.585862e-01  0.000000e+00  0.000000  0.000000  1.880136e-16   
11  7.380893e-01  0.000000e+00  0.000000  0.000000 -4.000000e-01   

               K             L  
0   0.000000e+00  0.000000e+00  
1   5.538401e-02 -3.248810e-02  
2   4.007535e-18 -1.597507e-18  
3  -1.107680e-01  6.497620e-02  
4  -7.440681e-01  4.364682e-01  
5   6.195773e-01  6.742457e-01  
6  -1.398781e-17  3.178480e-17  
7   2.171397e-01 -3.867955e-01  
8  -4.209425e-16 -1.665899e-16  
9  -7.100716e-16 -4.000000e-01  
10  1.281102e-15  4.545318e-16  
11 -1.420143e-15  2.000000e-01

In [55]:
#The strength of the themes are represented in the diagonals of this matrix
s

array([12.728, 10.577,  8.848,  1.242,  1.061,  0.407,  0.   ,  0.   ,
        0.   ])

In [56]:
np.diag(s[:3])

array([[12.728,  0.   ,  0.   ],
       [ 0.   , 10.577,  0.   ],
       [ 0.   ,  0.   ,  8.848]])

In [57]:
#The themes to columns matrix
VT

array([[-0.577, -0.577, -0.577,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ],
       [ 0.   ,  0.   ,  0.   , -0.638, -0.512, -0.575,  0.   ,  0.   ,
         0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , -0.476, -0.558,
        -0.68 ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.296,  0.626,
        -0.721],
       [-0.   , -0.   , -0.   ,  0.653, -0.756, -0.051,  0.   ,  0.   ,
         0.   ],
       [-0.   , -0.   , -0.   ,  0.   ,  0.   ,  0.   ,  0.828, -0.545,
        -0.133],
       [ 0.   ,  0.   ,  0.   , -0.408, -0.408,  0.816,  0.   ,  0.   ,
         0.   ],
       [ 0.816, -0.408, -0.408,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ],
       [ 0.   , -0.707,  0.707,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ]])

In [39]:
VT.shape

(9, 9)

In [59]:
b = ['Chicken','Mutton','Paneer','ChowMein','SpringRolls','Momo','Sushi','Ramen','Tempura']
dt = pd.DataFrame(VT,columns = b)
dt

Chicken    Mutton    Paneer  ChowMein  SpringRolls      Momo     Sushi  \
0 -0.577350 -0.577350 -0.577350  0.000000     0.000000  0.000000  0.000000   
1  0.000000  0.000000  0.000000 -0.637875    -0.512261 -0.575068  0.000000   
2  0.000000  0.000000  0.000000  0.000000     0.000000  0.000000 -0.476163   
3  0.000000  0.000000  0.000000  0.000000     0.000000  0.000000  0.296110   
4 -0.000000 -0.000000 -0.000000  0.653030    -0.755593 -0.051282  0.000000   
5 -0.000000 -0.000000 -0.000000  0.000000     0.000000  0.000000  0.828002   
6  0.000000  0.000000  0.000000 -0.408248    -0.408248  0.816497  0.000000   
7  0.816497 -0.408248 -0.408248  0.000000     0.000000  0.000000  0.000000   
8  0.000000 -0.707107  0.707107  0.000000     0.000000  0.000000  0.000000   

      Ramen   Tempura  
0  0.000000  0.000000  
1  0.000000  0.000000  
2 -0.557638 -0.679933  
3  0.626381 -0.721087  
4  0.000000  0.000000  
5 -0.544690 -0.133137  
6  0.000000  0.000000  
7  0.000000  0.000000  
8  0.000000  0.000000

In [61]:
dat = pd.read_csv('FoodRatings_all_same_5.csv')
dat = dat.drop(['Name'], axis=1)
dat

Chicken  Mutton  Paneer  ChowMein  SpringRolls  Momo  Sushi  Ramen  \
0         5       5       5         0            0     0      0      0   
1         5       5       5         0            0     0      0      0   
2         5       5       5         0            0     0      0      0   
3         5       5       5         0            0     0      0      0   
4         0       0       0         5            5     5      0      0   
5         0       0       0         5            5     5      0      0   
6         0       0       0         5            5     5      0      0   
7         0       0       0         5            5     5      0      0   
8         0       0       0         0            0     0      5      5   
9         0       0       0         0            0     0      5      5   
10        0       0       0         0            0     0      5      5   
11        0       0       0         0            0     0      5      5   

    Tempura  
0         0  
1         0  
2         0  
3         0  
4         0  
5         0  
6         0  
7         0  
8         5  
9         5  
10        5  
11        5

In [63]:
U, s, VT = np.linalg.svd(dat, full_matrices=True) 

In [64]:
U

array([[ 0.   ,  0.   , -0.5  ,  0.866,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   , -0.5  , -0.289,  0.816, -0.   ,  0.   ,  0.   ,
         0.   , -0.   , -0.   , -0.   ],
       [ 0.   ,  0.   , -0.5  , -0.289, -0.408, -0.177,  0.354,  0.354,
         0.354, -0.177, -0.177, -0.177],
       [ 0.   ,  0.   , -0.5  , -0.289, -0.408,  0.177, -0.354, -0.354,
        -0.354,  0.177,  0.177,  0.177],
       [-0.5  ,  0.   ,  0.   ,  0.   ,  0.   ,  0.125,  0.75 , -0.25 ,
        -0.25 ,  0.125,  0.125,  0.125],
       [-0.5  ,  0.   ,  0.   ,  0.   ,  0.   ,  0.125, -0.25 ,  0.75 ,
        -0.25 ,  0.125,  0.125,  0.125],
       [-0.5  ,  0.   ,  0.   ,  0.   ,  0.   , -0.375, -0.25 , -0.25 ,
        -0.25 , -0.375, -0.375, -0.375],
       [-0.5  ,  0.   ,  0.   ,  0.   ,  0.   ,  0.125, -0.25 , -0.25 ,
         0.75 ,  0.125,  0.125,  0.125],
       [ 0.   , -0.5  ,  0.   ,  0.   ,  0.   ,  0.75 ,  0.   ,  0.   ,
         0.   , -0.25 , 

In [65]:
s

array([17.321, 17.321, 17.321,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ])

In [66]:
VT

array([[-0.   , -0.   , -0.   , -0.577, -0.577, -0.577,  0.   ,  0.   ,
         0.   ],
       [-0.   , -0.   , -0.   ,  0.   ,  0.   ,  0.   , -0.577, -0.577,
        -0.577],
       [-0.577, -0.577, -0.577,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ],
       [ 0.816, -0.408, -0.408,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ],
       [-0.   ,  0.707, -0.707, -0.   , -0.   , -0.   ,  0.   ,  0.   ,
         0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , -0.707,
         0.707],
       [ 0.   ,  0.   ,  0.   ,  0.816, -0.408, -0.408,  0.   ,  0.   ,
         0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   , -0.707,  0.707,  0.   ,  0.   ,
         0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.816, -0.408,
        -0.408]])

In [67]:
dat = pd.read_csv('FoodRatings_all_same_5_4_3.csv')
dat = dat.drop(['Name'], axis=1)
dat

Chicken  Mutton  Paneer  ChowMein  SpringRolls  Momo  Sushi  Ramen  \
0         5       5       5         0            0     0      0      0   
1         5       5       5         0            0     0      0      0   
2         5       5       5         0            0     0      0      0   
3         5       5       5         0            0     0      0      0   
4         0       0       0         4            4     4      0      0   
5         0       0       0         4            4     4      0      0   
6         0       0       0         4            4     4      0      0   
7         0       0       0         4            4     4      0      0   
8         0       0       0         0            0     0      3      3   
9         0       0       0         0            0     0      3      3   
10        0       0       0         0            0     0      3      3   
11        0       0       0         0            0     0      3      3   

    Tempura  
0         0  
1         0  
2         0  
3         0  
4         0  
5         0  
6         0  
7         0  
8         3  
9         3  
10        3  
11        3

In [68]:
U, s, VT = np.linalg.svd(dat, full_matrices=True) 

In [69]:
U

array([[-0.5  ,  0.   ,  0.   ,  0.866,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ],
       [-0.5  ,  0.   ,  0.   , -0.289,  0.816, -0.   ,  0.   ,  0.   ,
         0.   , -0.   , -0.   , -0.   ],
       [-0.5  ,  0.   ,  0.   , -0.289, -0.408, -0.177,  0.354,  0.354,
         0.354, -0.177, -0.177, -0.177],
       [-0.5  ,  0.   ,  0.   , -0.289, -0.408,  0.177, -0.354, -0.354,
        -0.354,  0.177,  0.177,  0.177],
       [ 0.   , -0.5  ,  0.   ,  0.   ,  0.   ,  0.125, -0.25 , -0.25 ,
         0.75 ,  0.125,  0.125,  0.125],
       [ 0.   , -0.5  ,  0.   ,  0.   ,  0.   ,  0.125, -0.25 ,  0.75 ,
        -0.25 ,  0.125,  0.125,  0.125],
       [ 0.   , -0.5  ,  0.   ,  0.   ,  0.   , -0.375, -0.25 , -0.25 ,
        -0.25 , -0.375, -0.375, -0.375],
       [ 0.   , -0.5  ,  0.   ,  0.   ,  0.   ,  0.125,  0.75 , -0.25 ,
        -0.25 ,  0.125,  0.125,  0.125],
       [ 0.   ,  0.   , -0.5  ,  0.   ,  0.   ,  0.75 ,  0.   ,  0.   ,
         0.   , -0.25 , 

In [70]:
s

array([17.321, 13.856, 10.392,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ])

In [71]:
VT

array([[-0.577, -0.577, -0.577,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ],
       [-0.   , -0.   , -0.   , -0.577, -0.577, -0.577,  0.   ,  0.   ,
         0.   ],
       [-0.   , -0.   , -0.   ,  0.   ,  0.   ,  0.   , -0.577, -0.577,
        -0.577],
       [ 0.816, -0.408, -0.408,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ],
       [-0.   ,  0.707, -0.707, -0.   , -0.   , -0.   ,  0.   ,  0.   ,
         0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , -0.707,
         0.707],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.816, -0.408,
        -0.408],
       [ 0.   ,  0.   ,  0.   ,  0.   , -0.707,  0.707,  0.   ,  0.   ,
         0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.816, -0.408, -0.408,  0.   ,  0.   ,
         0.   ]])